/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iudigital.exceptions.java.presentacion;

import com.iudigital.exceptions.java.controller.FuncionariosController;
import com.iudigital.exceptions.java.controller.PersonaController;
import com.iudigital.exceptions.java.domain.Funcionarios;
import com.iudigital.exceptions.java.domain.Persona;
import java.sql.Array;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev1
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DefaultTableModel model;

    public Main() {
        initComponents();
        model = (DefaultTableModel) TableFuncionario.getModel();
        rellenarTabla();
        
        //modeloComboFuncionario = ComboBoxFuncionarios.getModel();
        
        
        String[] funcionariosLista = {"Uno", "Dos"};
        ComboBoxFuncionarios.setModel(new DefaultComboBoxModel(funcionariosLista));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        crearPersonaTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreCrearLabel = new javax.swing.JLabel();
        nombreCrear1 = new javax.swing.JLabel();
        nombreCrear2 = new javax.swing.JLabel();
        nombreCrear3 = new javax.swing.JLabel();
        nombreCrear4 = new javax.swing.JLabel();
        nombreCrear5 = new javax.swing.JLabel();
        nombreCrear6 = new javax.swing.JLabel();
        nombreCrear8 = new javax.swing.JLabel();
        nombreCrear7 = new javax.swing.JLabel();
        nombreCrear = new javax.swing.JTextField();
        estadoCivilCrear = new javax.swing.JTextField();
        direccionCrear = new javax.swing.JTextField();
        tipoIdentificacionCrear = new javax.swing.JTextField();
        numeroIdentificacionCrear = new javax.swing.JTextField();
        apellidosCrear = new javax.swing.JTextField();
        telefonoCrear = new javax.swing.JTextField();
        sexoCrear = new javax.swing.JComboBox<>();
        fechaDeNacimientoCrear = new javax.swing.JTextField();
        ButtonGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFuncionario = new javax.swing.JTable();
        LabelIdFuncionario = new javax.swing.JLabel();
        idFuncionarioCrear = new javax.swing.JTextField();
        actualizarPersonaTab = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreCrear9 = new javax.swing.JLabel();
        nombreCrear10 = new javax.swing.JLabel();
        nombreCrear11 = new javax.swing.JLabel();
        nombreActualizar = new javax.swing.JTextField();
        direccionActualizar = new javax.swing.JTextField();
        nombre11 = new javax.swing.JTextField();
        numeroIdentificacionActualizar = new javax.swing.JTextField();
        apellidosActualizar = new javax.swing.JTextField();
        estadoCivilActualizar = new javax.swing.JTextField();
        nombreCrear12 = new javax.swing.JLabel();
        telefonoActualizar = new javax.swing.JTextField();
        nombreCrear13 = new javax.swing.JLabel();
        sexoActualizar = new javax.swing.JComboBox<>();
        fechaDeNacimientoActualizar = new javax.swing.JTextField();
        nombreCrear14 = new javax.swing.JLabel();
        nombreCrear15 = new javax.swing.JLabel();
        nombreCrear16 = new javax.swing.JLabel();
        nombreCrear17 = new javax.swing.JLabel();
        ActualizarButton = new javax.swing.JButton();
        ComboBoxFuncionarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        nombre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Gestion de Funcionarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        nombreCrearLabel.setText("NOMBRES");

        nombreCrear1.setText("APELLIDOS");

        nombreCrear2.setText("TIPO IDENTIFICACION");

        nombreCrear3.setText("NUMERO IDENTIFICACION");

        nombreCrear4.setText("DIRECCION");

        nombreCrear5.setText("ESTADO CIVIL");

        nombreCrear6.setText("SEXO");

        nombreCrear8.setText("TELEFONO");

        nombreCrear7.setText("FECHA DE NACIMIENTO AAAA-MM-DD");

        nombreCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCrearActionPerformed(evt);
            }
        });

        estadoCivilCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilCrearActionPerformed(evt);
            }
        });

        direccionCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionCrearActionPerformed(evt);
            }
        });

        tipoIdentificacionCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoIdentificacionCrearActionPerformed(evt);
            }
        });

        numeroIdentificacionCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroIdentificacionCrearActionPerformed(evt);
            }
        });

        apellidosCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosCrearActionPerformed(evt);
            }
        });

        telefonoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoCrearActionPerformed(evt);
            }
        });

        sexoCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", " " }));
        sexoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoCrearActionPerformed(evt);
            }
        });

        fechaDeNacimientoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaDeNacimientoCrearActionPerformed(evt);
            }
        });

        ButtonGuardar.setText("Guardar");
        ButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonGuardarMouseClicked(evt);
            }
        });

        TableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Tipo identificacion", "Direccion", "Estado civil", "Numero identificacion", "Telefono", "Sexo", "Fecha de nacimiento", "ID funcionario"
            }
        ));
        jScrollPane1.setViewportView(TableFuncionario);

        LabelIdFuncionario.setText("ID FUNCIONARIO");

        idFuncionarioCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFuncionarioCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelIdFuncionario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idFuncionarioCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonoCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCrearLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCrear8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreCrear1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidosCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreCrear4)
                            .addComponent(nombreCrear6)
                            .addComponent(nombreCrear5)
                            .addComponent(estadoCivilCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonGuardar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombreCrear2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipoIdentificacionCrear)
                        .addComponent(nombreCrear3)
                        .addComponent(numeroIdentificacionCrear)
                        .addComponent(fechaDeNacimientoCrear)
                        .addComponent(nombreCrear7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCrearLabel)
                    .addComponent(nombreCrear4)
                    .addComponent(nombreCrear2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoIdentificacionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCrear1)
                    .addComponent(nombreCrear5)
                    .addComponent(nombreCrear3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(apellidosCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadoCivilCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numeroIdentificacionCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCrear8)
                    .addComponent(nombreCrear6)
                    .addComponent(nombreCrear7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDeNacimientoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelIdFuncionario)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ButtonGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idFuncionarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
        );

        nombreCrearLabel.getAccessibleContext().setAccessibleName("Nombre");
        LabelIdFuncionario.getAccessibleContext().setAccessibleName("idFuncionario");

        javax.swing.GroupLayout crearPersonaTabLayout = new javax.swing.GroupLayout(crearPersonaTab);
        crearPersonaTab.setLayout(crearPersonaTabLayout);
        crearPersonaTabLayout.setHorizontalGroup(
            crearPersonaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearPersonaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crearPersonaTabLayout.setVerticalGroup(
            crearPersonaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Crear Persona", crearPersonaTab);

        nombreCrear9.setText("NOMBRES");

        nombreCrear10.setText("DIRECCION");

        nombreCrear11.setText("TIPO IDENTIFICACION");

        nombreActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActualizarActionPerformed(evt);
            }
        });

        direccionActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActualizarActionPerformed(evt);
            }
        });

        nombre11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre11ActionPerformed(evt);
            }
        });

        numeroIdentificacionActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroIdentificacionActualizarActionPerformed(evt);
            }
        });

        apellidosActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActualizarActionPerformed(evt);
            }
        });

        estadoCivilActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilActualizarActionPerformed(evt);
            }
        });

        nombreCrear12.setText("TELEFONO");

        telefonoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActualizarActionPerformed(evt);
            }
        });

        nombreCrear13.setText("SEXO");

        sexoActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        sexoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActualizarActionPerformed(evt);
            }
        });

        fechaDeNacimientoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaDeNacimientoActualizarActionPerformed(evt);
            }
        });

        nombreCrear14.setText("FECHA DE NACIMIENTO AAAA-MM-DD");

        nombreCrear15.setText("APELLIDOS");

        nombreCrear16.setText("ESTADO CIVIL");

        nombreCrear17.setText("NUMERO IDENTIFICACION");

        ActualizarButton.setText("Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });

        ComboBoxFuncionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Persona");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBoxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(telefonoActualizar)
                                .addComponent(nombreCrear9)
                                .addComponent(nombreCrear12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombreActualizar)
                                .addComponent(apellidosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreCrear15, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCrear16, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreCrear10)
                            .addComponent(nombreCrear13)
                            .addComponent(estadoCivilActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ActualizarButton)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombreCrear11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombreCrear14)
                                .addComponent(nombre11)
                                .addComponent(numeroIdentificacionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fechaDeNacimientoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreCrear17, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCrear9)
                    .addComponent(nombreCrear10)
                    .addComponent(nombreCrear11))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCrear15)
                    .addComponent(nombreCrear16)
                    .addComponent(nombreCrear17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoCivilActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroIdentificacionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreCrear12)
                            .addComponent(nombreCrear13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(nombreCrear14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaDeNacimientoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(ActualizarButton)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout actualizarPersonaTabLayout = new javax.swing.GroupLayout(actualizarPersonaTab);
        actualizarPersonaTab.setLayout(actualizarPersonaTabLayout);
        actualizarPersonaTabLayout.setHorizontalGroup(
            actualizarPersonaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        actualizarPersonaTabLayout.setVerticalGroup(
            actualizarPersonaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarPersonaTabLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ActualizarPersona", actualizarPersonaTab);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCrearActionPerformed

    private void direccionCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionCrearActionPerformed

    private void tipoIdentificacionCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoIdentificacionCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoIdentificacionCrearActionPerformed

    private void apellidosCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosCrearActionPerformed

    private void estadoCivilCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilCrearActionPerformed

    private void telefonoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoCrearActionPerformed

    private void numeroIdentificacionCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroIdentificacionCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroIdentificacionCrearActionPerformed

    private void nombre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre8ActionPerformed

    private void sexoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoCrearActionPerformed

    private void fechaDeNacimientoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaDeNacimientoCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaDeNacimientoCrearActionPerformed

    private void nombreActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActualizarActionPerformed

    private void direccionActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActualizarActionPerformed

    private void nombre11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre11ActionPerformed

    private void numeroIdentificacionActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroIdentificacionActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroIdentificacionActualizarActionPerformed

    private void apellidosActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActualizarActionPerformed

    private void estadoCivilActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilActualizarActionPerformed

    private void telefonoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActualizarActionPerformed

    private void sexoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActualizarActionPerformed

    private void fechaDeNacimientoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaDeNacimientoActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaDeNacimientoActualizarActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    public void rellenarTabla() {
        FuncionariosController funcionariosController = new FuncionariosController();
        try {
            List<Funcionarios> funcionarios = funcionariosController.getAllFuncionarios();
            if (funcionarios.isEmpty()) {
                System.out.println("No hay datos");
            } else {
                model.setRowCount(0);

                funcionarios.forEach(persona -> {

                    model.insertRow(TableFuncionario.getRowCount(), new Object[]{
                        persona.getNombres(),
                        persona.getApellidos(),
                        persona.getTipoIdentificacion(),
                        persona.getApellidos(),
                        persona.getEstadoCivil(),
                        persona.getNumeroIdentificacion(),
                        persona.getTelefono(),
                        persona.getSexo(),
                        persona.getFechaNacimiento(),
                        persona.getIdentificacion()
                    });

                });
            }
            //System.out.println((String) sexoCrear.getSelectedItem());

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void rellenarComboxACtualizar() {
        FuncionariosController funcionariosController = new FuncionariosController();
        try {
            List<Funcionarios> funcionarios = funcionariosController.getAllFuncionarios();
            funcionarios.size();
            
            String[] funcionariosLista = new String [funcionarios.size()];
            
            int contador =0;
            
            if (funcionarios.isEmpty()) {
                System.out.println("No hay datos");
            } else {
                

                funcionarios.forEach(persona -> {
                    
                    

                    model.insertRow(TableFuncionario.getRowCount(), new Object[]{
                        persona.getNombres(),
                        persona.getApellidos(),
                        persona.getTipoIdentificacion(),
                        persona.getApellidos(),
                        persona.getEstadoCivil(),
                        persona.getNumeroIdentificacion(),
                        persona.getTelefono(),
                        persona.getSexo(),
                        persona.getFechaNacimiento(),
                        persona.getIdentificacion()
                    });
                   
                });
            }
            //System.out.println((String) sexoCrear.getSelectedItem());

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void guardarFuncionarioDesdeFormulario() {

        try {
            Funcionarios funcionario = new Funcionarios();
            FuncionariosController funcionariosController = new FuncionariosController();
            
            PersonaController personaController = new PersonaController();

            funcionario.setNombres(nombreCrear.getText());
            funcionario.setApellidos(apellidosCrear.getText());
            funcionario.setDireccion(direccionCrear.getText());
            funcionario.setEstadoCivil(estadoCivilCrear.getText());
            funcionario.setTipoIdentificacion(tipoIdentificacionCrear.getText());
            

            funcionario.setSexo((String) sexoCrear.getSelectedItem());
            funcionario.setFechaNacimiento(LocalDate.parse(fechaDeNacimientoCrear.getText()));
            
            funcionario.setNumeroIdentificacion(numeroIdentificacionCrear.getText());
            funcionario.setIdentificacion(Integer.parseInt(idFuncionarioCrear.getText()));

            personaController.createPersona(funcionario);
            
            funcionario.setIdPersona(personaController.obtenerUltimoIdPersona());


            funcionariosController.createFuncionario(funcionario);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void ButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonGuardarMouseClicked
        System.out.println(nombreCrear.getText());
        guardarFuncionarioDesdeFormulario();
        rellenarTabla();

    }//GEN-LAST:event_ButtonGuardarMouseClicked

    private void idFuncionarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFuncionarioCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFuncionarioCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JComboBox<String> ComboBoxFuncionarios;
    private javax.swing.JLabel LabelIdFuncionario;
    private javax.swing.JTable TableFuncionario;
    private javax.swing.JPanel actualizarPersonaTab;
    private javax.swing.JTextField apellidosActualizar;
    private javax.swing.JTextField apellidosCrear;
    private javax.swing.JPanel crearPersonaTab;
    private javax.swing.JTextField direccionActualizar;
    private javax.swing.JTextField direccionCrear;
    private javax.swing.JTextField estadoCivilActualizar;
    private javax.swing.JTextField estadoCivilCrear;
    private javax.swing.JTextField fechaDeNacimientoActualizar;
    private javax.swing.JTextField fechaDeNacimientoCrear;
    private javax.swing.JTextField idFuncionarioCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombre11;
    private javax.swing.JTextField nombre8;
    private javax.swing.JTextField nombreActualizar;
    private javax.swing.JTextField nombreCrear;
    private javax.swing.JLabel nombreCrear1;
    private javax.swing.JLabel nombreCrear10;
    private javax.swing.JLabel nombreCrear11;
    private javax.swing.JLabel nombreCrear12;
    private javax.swing.JLabel nombreCrear13;
    private javax.swing.JLabel nombreCrear14;
    private javax.swing.JLabel nombreCrear15;
    private javax.swing.JLabel nombreCrear16;
    private javax.swing.JLabel nombreCrear17;
    private javax.swing.JLabel nombreCrear2;
    private javax.swing.JLabel nombreCrear3;
    private javax.swing.JLabel nombreCrear4;
    private javax.swing.JLabel nombreCrear5;
    private javax.swing.JLabel nombreCrear6;
    private javax.swing.JLabel nombreCrear7;
    private javax.swing.JLabel nombreCrear8;
    private javax.swing.JLabel nombreCrear9;
    private javax.swing.JLabel nombreCrearLabel;
    private javax.swing.JTextField numeroIdentificacionActualizar;
    private javax.swing.JTextField numeroIdentificacionCrear;
    private javax.swing.JComboBox<String> sexoActualizar;
    private javax.swing.JComboBox<String> sexoCrear;
    private javax.swing.JTextField telefonoActualizar;
    private javax.swing.JTextField telefonoCrear;
    private javax.swing.JTextField tipoIdentificacionCrear;
    // End of variables declaration//GEN-END:variables
}
